---

- name: install > Stat bin
  ansible.builtin.stat:
    path: "{{ manala_gomplate_bin }}"
  register: __manala_gomplate_bin_stat_result

- name: install > Get latest version
  ansible.builtin.uri:
    url: https://github.com/hairyhenderson/gomplate/releases/latest
    return_content: false
  register: __manala_gomplate_version_latest
  when:
    - not __manala_gomplate_bin_stat_result.stat.exists
    - manala_gomplate_version is none

- name: install > Install
  ansible.builtin.get_url:
    url: "{{
      'https://github.com/hairyhenderson/gomplate/releases/download/v%(version)s/gomplate_linux-%(architecture)s'|format(
        version=manala_gomplate_version|ternary(
          manala_gomplate_version,
          __manala_gomplate_version_latest.url|default|regex_replace('.+/v(\\d+\\.\\d+\\.\\d+)$', '\\1')
        ),
        architecture=ansible_architecture|manala.roles.gomplate_architecture,
      )
    }}"
    dest: "{{ manala_gomplate_bin }}"
    owner: root
    group: root
    mode: "0755"
  when: not __manala_gomplate_bin_stat_result.stat.exists
