---

- name: Install > Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
  loop:
    - |
      {{
        manala_postgresql_install_packages | default(manala_postgresql_install_packages_default, True)
        + (
          (manala_postgresql_databases | length > 0)
          or (manala_postgresql_privileges | length > 0)
          or (manala_postgresql_roles | length > 0)
        ) | ternary(
          (ansible_python.version.major == 2) | ternary(
            ['python-psycopg2'],
            ['python3-psycopg2']
          ),
          []
        )
      }}
