---

- name: Privileges > Users
  community.postgresql.postgresql_user:
    name: "{{ item.role }}"
    state: "{{ item.state | default('present') }}"
    # Login
    login_host: "{{ item.login_host | default(manala_postgresql_login_host | default(omit, True), True) }}"
    login_port: "{{ item.login_port | default(manala_postgresql_login_port | default(omit, True), True) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(manala_postgresql_login_unix_socket | default(omit, True), True) }}"
    login_db: "{{ item.database }}"
    login_user: "{{ item.login_user | default(manala_postgresql_login_user | default(omit, True), True) }}"
    login_password: "{{ item.login_password | default(manala_postgresql_login_password | default(omit, True), True) }}"
  loop: "{{ manala_postgresql_privileges }}"

- name: Privileges > Handle
  community.postgresql.postgresql_privs:
    roles: "{{ item.role }}"
    type: "{{ item.type | default(omit) }}"
    privs: |-
      {{ item.privileges | join(',') }}
    objs: |-
      {{ item.objects | default(omit) | join(',') }}
    state: "{{ item.state | default('present') }}"
    # Login
    login_host: "{{ item.login_host | default(manala_postgresql_login_host | default(omit, True), True) }}"
    login_port: "{{ item.login_port | default(manala_postgresql_login_port | default(omit, True), True) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(manala_postgresql_login_unix_socket | default(omit, True), True) }}"
    login_db: "{{ item.database }}"
    login_user: "{{ item.login_user | default(manala_postgresql_login_user | default(omit, True), True) }}"
    login_password: "{{ item.login_password | default(manala_postgresql_login_password | default(omit, True), True) }}"
  loop: "{{ manala_postgresql_privileges }}"
