---

- name: config > Redis server template
  template:
    src: "{{ manala_redis_config_template|ternary(manala_redis_config_template, 'config/default.j2') }}"
    dest: "{{ manala_redis_config_file }}"
    owner: redis
    group: redis
    mode: "0640"
  when: manala_redis_server and ((manala_redis_config_template is not none) or (manala_redis_config|length))
  notify:
    - redis restart

- name: config > Redis sentinel template
  lineinfile:
    dest: "{{ manala_redis_sentinel_config_file }}"
    regexp: "^{{ item.key }} (.*)$"
    line: "{{ item.key }} {{ item.value }}"
  when: manala_redis_sentinel and (manala_redis_sentinel_config|length)
  with_dict: "{{ manala_redis_sentinel_config }}"
  notify:
    - redis-sentinel restart
