---

# Elasticsearch version. Available values are '~' (autodetect), '1.5', '1.6', '1.7', '2', '5', '6', '7'
manala_elasticsearch_version: ~

# Install
manala_elasticsearch_install_packages: ~
manala_elasticsearch_install_packages_default:
  - elasticsearch

# Config
manala_elasticsearch_config_file: /etc/elasticsearch/elasticsearch.yml
manala_elasticsearch_config_template: ~
manala_elasticsearch_config: []

# Plugins
manala_elasticsearch_plugins: []

# Environment
manala_elasticsearch_environment_file: /etc/default/elasticsearch
manala_elasticsearch_environment_template: ~
manala_elasticsearch_environment: []
