---

- name: Shared > Ensure release targets are absent
  ansible.builtin.file:
    path: "{{ deploy_helper.new_release_path ~ '/' ~ item }}"
    state: absent
  loop: "{{ manala_deploy_shared_files + manala_deploy_shared_dirs }}"

- name: Shared > Stat shared files
  ansible.builtin.stat:
    path: "{{ deploy_helper.shared_path ~ '/' ~ item }}"
  register: __manala_deploy_shared_files_stats_output
  loop: "{{ manala_deploy_shared_files }}"

- name: Shared > Ensure shared directories files are present
  ansible.builtin.file:  # noqa: risky-file-permissions
    path: "{{ (deploy_helper.shared_path ~ '/' ~ item) | dirname }}"
    state: directory
  loop: "{{ manala_deploy_shared_files | flatten }}"
  loop_control:
    index_var: index
  when: not __manala_deploy_shared_files_stats_output.results[index].stat.exists

- name: Shared > Ensure shared files are present
  ansible.builtin.file:  # noqa: risky-file-permissions
    path: "{{ deploy_helper.shared_path ~ '/' ~ item }}"
    state: touch
  loop: "{{ manala_deploy_shared_files | flatten }}"
  loop_control:
    index_var: index
  when: not __manala_deploy_shared_files_stats_output.results[index].stat.exists

- name: Shared > Ensure shared dirs are present
  ansible.builtin.file:  # noqa: risky-file-permissions
    path: "{{ deploy_helper.shared_path ~ '/' ~ item }}"
    state: directory
    follow: true
  loop: "{{ manala_deploy_shared_dirs }}"

- name: Shared > Links
  ansible.builtin.file:
    path: "{{ deploy_helper.new_release_path ~ '/' ~ item }}"
    src: "{{ (deploy_helper.shared_path ~ '/' ~ item) | relpath((deploy_helper.new_release_path ~ '/' ~ item) | dirname) }}"
    state: link
  loop: "{{ manala_deploy_shared_files + manala_deploy_shared_dirs }}"
