---

- name: databases > Create Influx databases
  command: "{{ manala_influxdb_influx_bin }} -execute 'CREATE DATABASE \"{{ item }}\"'"
  loop: "{{ manala_influxdb_databases }}"
  changed_when: false
