---

dependencies: []

galaxy_info:

  role_name:           cron
  author:              Manala
  company:             Manala
  description:         Handle cron
  license:             MIT
  min_ansible_version: 2.5.0
  issue_tracker_url:   https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - system
    - cron
