---

- name: config > Directory
  file:
    path: "{{ manala_rsyslog_config_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: config > Template
  template:
    src: "{{ manala_rsyslog_config_template|default('config/_default.j2', true) }}"
    dest: "{{ manala_rsyslog_config_file }}"
    owner: root
    group: root
    mode: "0644"
  when: manala_rsyslog_config_template
        or manala_rsyslog_config
  notify:
    - rsyslog restart
