---

- name: configs > Directory
  file:
    path: "{{ manala_rsyslog_configs_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: manala_rsyslog_configs|length

- name: configs > Exclusive
  find:
    path: "{{ manala_rsyslog_configs_dir }}"
    patterns: "*"
  changed_when: false
  register: __manala_rsyslog_configs_exclusive_find
  when: manala_rsyslog_configs_exclusive

- name: configs > Templates present
  template:
    src: "{{ item.template }}"
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ query(
      'manala_templates_exclusive',
      manala_rsyslog_configs,
      __manala_rsyslog_configs_exclusive_find.files|default([]),
      manala_rsyslog_configs_dir,
      manala_rsyslog_configs_defaults.template|default('configs/_default.j2', true),
      wantstate='present'
    )
  }}"
  notify:
    - rsyslog restart

- name: configs > Files absent
  file:
    path: "{{ item.file }}"
    state: absent
  loop: "{{ query(
      'manala_templates_exclusive',
      manala_rsyslog_configs,
      __manala_rsyslog_configs_exclusive_find.files|default([]),
      manala_rsyslog_configs_dir,
      manala_rsyslog_configs_defaults.template|default('configs/_default.j2', true),
      wantstate='absent'
    )
  }}"
  notify:
    - rsyslog restart
