---

- name: install > Packages
  apt:
    name: "{{ manala_rsyslog_install_packages|default(manala_rsyslog_install_packages_default, True) }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
