---

# Install
manala_mysql_install_packages: ~
manala_mysql_install_packages_default: |
  {{
    manala_mysql_server | ternary(
      ['mysql-server', 'mysql-client'],
      ['mysql-client']
    )
  }}
manala_mysql_install_python_packages: |
  {{
    (ansible_python.version.major == 2) | ternary(
      ['python-mysqldb'],
      ['python3-mysqldb']
    )
  }}

# Server
manala_mysql_server: true

# Config
manala_mysql_config_file: /etc/mysql/my.cnf
manala_mysql_config_alternative: ~
manala_mysql_config_template: ~
manala_mysql_config: ~

# Configs
manala_mysql_configs_exclusive: false
manala_mysql_configs_dir: /etc/mysql/conf.d
manala_mysql_configs_defaults: {}
manala_mysql_configs: []

# Data
manala_mysql_data_dir: ~
manala_mysql_data_dir_user: mysql
manala_mysql_data_dir_group: mysql
manala_mysql_data_dir_mode: "0750"
manala_mysql_data_dir_initialize: false

# Users
manala_mysql_users: []

# Databases
manala_mysql_databases: []

# Replications
manala_mysql_replications: []
