---

# Install
manala_mysql_install_packages: ~
manala_mysql_install_packages_default:
  - mysql-server
  - mysql-client

# Config
manala_mysql_config_file: /etc/mysql/my.cnf
manala_mysql_config_alternative: ~
manala_mysql_config_template: ~
manala_mysql_config: ~

# Configs
manala_mysql_configs_exclusive: false
manala_mysql_configs_dir: /etc/mysql/conf.d
manala_mysql_configs_template: ~ # Deprecated
manala_mysql_configs_defaults:
  template: "{{ manala_mysql_configs_template }}" # Ensure backward compatibility
manala_mysql_configs: []

# Data dir
manala_mysql_data_dir: ~
manala_mysql_data_dir_user: mysql
manala_mysql_data_dir_group: mysql
manala_mysql_data_dir_mode: "0750"
manala_mysql_data_dir_initialize: false

# Users
manala_mysql_users: []

# Databases
manala_mysql_databases: []

# Replications
manala_mysql_replications: []
