---

dependencies: []

galaxy_info:

  role_name: haproxy
  author: Manala
  company: Manala
  description: Handle haproxy
  license: MIT
  min_ansible_version: 2.15.0
  issue_tracker_url: https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - system
    - haproxy
