---

# Install
manala_dhcp_install_packages: ~
manala_dhcp_install_packages_default:
  - isc-dhcp-server

# Interfaces
manala_dhcp_interfaces_file: /etc/default/isc-dhcp-server
manala_dhcp_interfaces: []

# Config
manala_dhcp_config_file: /etc/dhcp/dhcpd.conf
manala_dhcp_config_template: ~
manala_dhcp_config_content: ~
