language: generic

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - VERBOSE=1

jobs:
  include:
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.6.5 PART=1/3
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.6.5 PART=2/3
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.6.5 PART=3/3
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=1/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=2/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=3/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=4/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=5/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=6/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.6.5 PART=7/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=1/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=2/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=3/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=4/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=5/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=6/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=debian.stretch  ANSIBLE_VERSION=2.6.5 PART=7/7
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=centos.7  ANSIBLE_VERSION=2.6.5 PART=1/1
      if: type = pull_request
    - stage: lint & test
      script: make lint && make test
      env:
        - DISTRIBUTIONS=ubuntu.xenial  ANSIBLE_VERSION=2.6.5 PART=1/1
      if: type = pull_request
    - stage: gitsplit
      script: make gitsplit
      if: branch = master AND type = push
