language: generic

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - VERBOSE=1
    - CACHE_DIR=${TRAVIS_BUILD_DIR}/.cache
  matrix:
    - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.3.2.0 PART=1/3
    - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.3.2.0 PART=2/3
    - DISTRIBUTIONS=debian.wheezy  ANSIBLE_VERSION=2.3.2.0 PART=3/3
    - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.3.2.0 PART=1/3
    - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.3.2.0 PART=2/3
    - DISTRIBUTIONS=debian.jessie  ANSIBLE_VERSION=2.3.2.0 PART=3/3
    - DISTRIBUTIONS=debian.stretch ANSIBLE_VERSION=2.3.2.0 PART=1/3
    - DISTRIBUTIONS=debian.stretch ANSIBLE_VERSION=2.3.2.0 PART=2/3
    - DISTRIBUTIONS=debian.stretch ANSIBLE_VERSION=2.3.2.0 PART=3/3
    - DISTRIBUTIONS=centos.7       ANSIBLE_VERSION=2.3.2.0 PART=1/3
    - DISTRIBUTIONS=centos.7       ANSIBLE_VERSION=2.3.2.0 PART=2/3
    - DISTRIBUTIONS=centos.7       ANSIBLE_VERSION=2.3.2.0 PART=3/3
    - DISTRIBUTIONS=ubuntu.xenial  ANSIBLE_VERSION=2.3.2.0 PART=1/3
    - DISTRIBUTIONS=ubuntu.xenial  ANSIBLE_VERSION=2.3.2.0 PART=2/3
    - DISTRIBUTIONS=ubuntu.xenial  ANSIBLE_VERSION=2.3.2.0 PART=3/3

script:
  - make lint.diff
  - make test.diff

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
