---

dependencies: []

galaxy_info:

  role_name: vim
  author: Manala
  company: Manala
  description: Handle vim
  license: MIT
  min_ansible_version: 2.18.0
  issue_tracker_url: https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - system
    - vim
