---

# Flags
__manala_apt: |
  {{
    {
      'update': False
    } | combine(
      manala | default({}),
      manala_apt
    )
  }}

# Repositories
manala_apt_repositories_patterns:
  default:
    source: deb http://deb.debian.org/debian {{ ansible_distribution_release }} {{ manala_apt_components | flatten | join(' ') }}
    pin: release a={{ ansible_distribution_release }}
  security:
    source: >-
      deb http://security.debian.org/debian-security
      {{ ansible_distribution_release }}{{ (ansible_distribution_release in ['buster']) | ternary('/updates', '-security') }}
      {{ manala_apt_components | flatten | join(' ') }}
  security_src:
    source: >-
      deb-src http://security.debian.org/debian-security
      {{ ansible_distribution_release }}{{ (ansible_distribution_release in ['buster']) | ternary('/updates', '-security') }}
      {{ manala_apt_components | flatten | join(' ') }}
  updates:
    source: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-updates {{ manala_apt_components | flatten | join(' ') }}
  updates_src:
    source: deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-updates {{ manala_apt_components | flatten | join(' ') }}
  backports:
    source: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports {{ manala_apt_components | flatten | join(' ') }}
    pin: release a={{ ansible_distribution_release }}-backports
  backports_sloppy:
    source: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports-sloppy {{ manala_apt_components | flatten | join(' ') }}
    pin: release a={{ ansible_distribution_release }}-backports-sloppy
  multimedia:
    source: deb http://www.deb-multimedia.org {{ ansible_distribution_release }} main
    key: multimedia
    file: multimedia.list
  multimedia_backports:
    source: deb http://www.deb-multimedia.org {{ ansible_distribution_release }}-backports main
    key: multimedia
    file: multimedia_backports.list
  nginx:
    source: deb http://nginx.org/packages/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx
    key: nginx
  bearstech:
    source: deb http://deb.bearstech.com/debian {{ ansible_distribution_release }}-bearstech main
    key: bearstech
  nodesource_4:
    source: deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_6:
    source: deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_7:
    source: deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_8:
    source: deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_9:
    source: deb https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_10:
    source: deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_12:
    source: deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_14:
    source: deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_16:
    source: deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_18:
    source: deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main
    key: nodesource
  nodesource_20:
    source: deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main
    key: nodesource
  mysql_5_7:
    source: deb http://repo.mysql.com/apt/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} mysql-5.7
    key: mysql
  mysql_8_0:
    source: deb http://repo.mysql.com/apt/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} mysql-8.0
    key: mysql
  mariadb_10_1:
    source: deb http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian {{ ansible_distribution_release }} main
    key: mariadb
  mariadb_10_2:
    source: deb http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian {{ ansible_distribution_release }} main
    key: mariadb
  mariadb_10_3:
    source: deb https://downloads.mariadb.com/MariaDB/mariadb-10.3/repo/debian {{ ansible_distribution_release }} main
    key: mariadb
  mariadb_10_4:
    source: deb https://downloads.mariadb.com/MariaDB/mariadb-10.4/repo/debian {{ ansible_distribution_release }} main
    key: mariadb
  mariadb_10_5:
    source: deb https://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/debian {{ ansible_distribution_release }} main
    key: mariadb
  mariadb_10_6:
    source: deb https://downloads.mariadb.com/MariaDB/mariadb-10.6/repo/debian {{ ansible_distribution_release }} main
    key: mariadb
  mariadb_10_11:
    source: deb https://downloads.mariadb.com/MariaDB/mariadb-10.11/repo/debian {{ ansible_distribution_release }} main
    key: mariadb
  maxscale_2_3:
    source: deb https://downloads.mariadb.com/MaxScale/2.3/debian {{ ansible_distribution_release }} main
    key: maxscale
  maxscale_2_4:
    source: deb https://downloads.mariadb.com/MaxScale/2.4/debian {{ ansible_distribution_release }} main
    key: mariadb_enterprise
  maxscale_2_5:
    source: deb https://downloads.mariadb.com/MaxScale/2.5/debian {{ ansible_distribution_release }} main
    key: mariadb_enterprise
  maxscale_6_1:
    source: deb https://downloads.mariadb.com/MaxScale/6.1/debian {{ ansible_distribution_release }} main
    key: mariadb_enterprise
  postgresql:
    source: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    key: postgresql
  mongodb_4_2:
    source: deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/4.2 main
    key: mongodb_4_2
  mongodb_4_4:
    source: deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/4.4 main
    key: mongodb_4_4
  varnish_4_0:
    source: deb https://packagecloud.io/varnishcache/varnish40/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
    key: varnish_4_0
  varnish_6_1:
    source: deb https://packagecloud.io/varnishcache/varnish61/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
    key: varnish_6_1
  jenkins:
    source: deb http://pkg.jenkins-ci.org/debian binary/
    key: jenkins
  sensu-go:
    source: deb https://packagecloud.io/sensu/stable/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main
    key: sensu-go
  rabbitmq:
    source: deb http://www.rabbitmq.com/debian/ testing main
    key: rabbitmq
  proxmox:
    source: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    key: proxmox
  proxmox_enterprise:
    source: deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
    key: proxmox
  galera_4:
    source: deb https://releases.galeracluster.com/galera-4/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  galera_4_7:
    source: deb https://releases.galeracluster.com/galera-4.7/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  galera_4_8:
    source: deb https://releases.galeracluster.com/galera-4.8/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  galera_4_10:
    source: deb https://releases.galeracluster.com/galera-4.10/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  mysql_wsrep_5_7:
    source: deb [trusted=yes] http://releases.galeracluster.com/mysql-wsrep-5.7/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  mysql_wsrep_8_0:
    source: deb https://releases.galeracluster.com/mysql-wsrep-8.0/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  mysql_wsrep_8_0_22:
    source: deb https://releases.galeracluster.com/mysql-wsrep-8.0.22-26.5/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  mysql_wsrep_8_0_23:
    source: deb https://releases.galeracluster.com/mysql-wsrep-8.0.23-26.6/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  mysql_wsrep_8_0_26:
    source: deb https://releases.galeracluster.com/mysql-wsrep-8.0.26-26.8/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    key: galera
  grafana:
    source: deb https://apt.grafana.com stable main
    key: grafana
  elasticsearch_5:
    source: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    key: elasticsearch
  elasticsearch_6:
    source: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    key: elasticsearch
  elasticsearch_7:
    source: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    key: elasticsearch
  ansible:
    source: >-
      deb http://ppa.launchpad.net/ansible/ansible/ubuntu
      {{ {'buster': 'bionic', 'bullseye': 'focal'}[ansible_distribution_release] }}
      main
    key: ansible
  blackfire:
    source: deb http://packages.blackfire.io/debian any main
    key: blackfire
  gitlab-ce:
    source: deb https://packages.gitlab.com/gitlab/gitlab-ce/debian/ {{ ansible_distribution_release }} main
    key: gitlab
  aptly:
    source: deb http://repo.aptly.info/ squeeze main
    key: aptly
  docker:
    source: >-
      deb [arch={{ ansible_architecture | manala.roles.apt_architecture }}]
      https://download.docker.com/linux/{{ ansible_lsb.id | default(ansible_distribution) | lower }} {{ ansible_distribution_release }} stable
    key: docker
  manala:
    source: deb http://debian.manala.io {{ ansible_distribution_release }} main
    key: manala
  newrelic:
    source: deb http://apt.newrelic.com/debian/ newrelic non-free
    key: newrelic
  newrelic-infra:
    source: >-
      deb [arch={{ ansible_architecture | manala.roles.apt_architecture }}]
      https://download.newrelic.com/infrastructure_agent/linux/apt {{ ansible_distribution_release }} main
    key: newrelic-infra
  influxdata:
    source: deb https://repos.influxdata.com/debian {{ ansible_distribution_release }} stable
    key: influxdata
  yarn:
    source: deb https://dl.yarnpkg.com/debian/ stable main
    key: yarn
  sury_php:
    source: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    key: sury_php
  percona:
    source: deb http://repo.percona.com/apt {{ ansible_distribution_release }} main
    key: percona
  matomo:
    source: deb http://debian.matomo.org/ piwik main
    key: matomo
  owncloud:
    source: deb http://download.owncloud.org/download/repositories/production/Debian_{{ ansible_distribution_major_version }}.0/ /
    key: owncloud
  mica:
    source: deb https://obiba.jfrog.io/artifactory/debian-local all main
    key: mica
  glusterfs_6:
    source: >-
      deb https://download.gluster.org/pub/gluster/glusterfs/6/LATEST/Debian/{{ ansible_distribution_release }}/{{
        ansible_architecture | manala.roles.apt_architecture
      }}/apt
      {{ ansible_distribution_release }} main
    key: glusterfs_6
  glusterfs_6_1:
    source: >-
      deb https://download.gluster.org/pub/gluster/glusterfs/6/6.1/Debian/{{ ansible_distribution_release }}/{{
        ansible_architecture | manala.roles.apt_architecture
      }}/apt
      {{ ansible_distribution_release }} main
    key: glusterfs_6
  glusterfs_6_10:
    source: >-
      deb https://download.gluster.org/pub/gluster/glusterfs/6/6.10/Debian/{{ ansible_distribution_release }}/{{
        ansible_architecture | manala.roles.apt_architecture
      }}/apt
      {{ ansible_distribution_release }} main
    key: glusterfs_6
  glusterfs_10_2:
    source: >-
      deb https://download.gluster.org/pub/gluster/glusterfs/10/10.2/Debian/{{ ansible_distribution_release }}/{{
        ansible_architecture | manala.roles.apt_architecture
      }}/apt
      {{ ansible_distribution_release }} main
    key: glusterfs_10
  haproxy_1_8:
    source: deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-1.8 main
    key: haproxy
  haproxy_2_0:
    source: deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-2.0 main
    key: haproxy
  haproxy_2_2:
    source: deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-2.2 main
    key: haproxy
  haproxy_2_4:
    source: deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-2.4 main
    key: haproxy
  haproxy_2_6:
    source: deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-2.6 main
    key: haproxy
  unifi:
    source: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
    key: unifi
  kopia:
    source: deb http://packages.kopia.io/apt/ stable main
    key: kopia
  symfony:
    source: deb https://dl.cloudsmith.io/public/symfony/stable/deb/debian {{ ansible_distribution_release }} main
    key: symfony
    file: symfony.list
  github_cli:
    source: deb https://cli.github.com/packages stable main
    key: github_cli
    file: github_cli.list

# Keys
manala_apt_keys_patterns:
  multimedia:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 65558117
  nginx:
    url: http://nginx.org/keys/nginx_signing.key
    id: 7BD9BF62
  bearstech:
    url: http://deb.bearstech.com/bearstech-archive.gpg
    id: 90158EE0
  nodesource:
    url: http://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 68576280
  mysql:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    id: 3A79BD29
  mariadb:
    url: https://raw.githubusercontent.com/MariaDB/mariadb.org-tools/master/release/create_package_tarballs/deb_files/MariaDB-C74CD1D8-public.asc
    id: C74CD1D8
  mariadb_enterprise:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: E3C94F49
  maxscale:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 28C12247
  postgresql:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8
  mongodb_4_2:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    id: 058F8B6B
  mongodb_4_4:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    id: 90CFB1F5
  varnish_4_0:
    url: https://packagecloud.io/varnishcache/varnish40/gpgkey
    id: DE3FFEA4
  varnish_6_1:
    url: https://packagecloud.io/varnishcache/varnish61/gpgkey
    id: 742D76CC
  jenkins:
    url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
    id: D50582E6
  sensu-go:
    url: https://packagecloud.io/sensu/stable/gpgkey
    id: 0A3F7426
  rabbitmq:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    id: 6026DFCA
  proxmox:
    url: http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg
    id: E2EF0603
  galera:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: BC19DDBA
  packagecloud:
    url: https://packagecloud.io/gpg.key
    id: D59097AB
  elasticsearch:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: D88E42B4
  gitlab:
    url: https://packages.gitlab.com/gpg.key
    id: 51312F3F
  aptly:
    url: https://www.aptly.info/pubkey.txt
    id: 624A8331
  docker:
    url: https://download.docker.com/linux/{{ ansible_lsb.id | default(ansible_distribution) | lower }}/gpg
    id: 0EBFCD88
  manala:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 1394DEA3
  newrelic:
    url: https://download.newrelic.com/548C16BF.gpg
    id: 548C16BF
  newrelic-infra:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    id: 8ECCE87C
  influxdata:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 7DF8B07E
  yarn:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    id: 86E50310
  sury_php:
    url: https://packages.sury.org/php/apt.gpg
    id: 95BD4743
  percona:
    url: https://github.com/percona/percona-repositories/raw/main/deb/percona-keyring.gpg
    id: 8507EFA5
  matomo:
    url: https://debian.matomo.org/repository.gpg
    id: 66FED89E
  owncloud:
    url: https://download.owncloud.org/download/repositories/production/Debian_{{ ansible_distribution_major_version }}.0/Release.key
    id: 479BC94B
  grafana:
    url: https://apt.grafana.com/gpg.key
    id: 2CF3C0C6
  blackfire:
    url: https://packages.blackfire.io/gpg.key
    id: 47312329
  mica:
    url: https://www.obiba.org/assets/obiba-pub.pem
    id: 7B0A831B
  glusterfs_6:
    url: https://download.gluster.org/pub/gluster/glusterfs/6/rsa.pub
    id: C2F8238C
  glusterfs_10:
    url: https://download.gluster.org/pub/gluster/glusterfs/10/rsa.pub
    id: C2F8238C
  ansible:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 7BB9C367
  haproxy:
    url: https://haproxy.debian.net/bernat.debian.org.gpg
    id: 353525F9
  unifi:
    url: https://dl.ubnt.com/unifi/unifi-repo.gpg
    id: 06E85760C0A52C50
  kopia:
    url: https://kopia.io/signing-key
    id: FD56A556
  github_cli:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    id: 75716059
  symfony:
    url: https://dl.cloudsmith.io/public/symfony/stable/gpg.99CEF8A62216B73D.key
    id: 2216B73D

# Preferences
manala_apt_preferences_patterns:
  vim: vim*
  git: git git-*
  php: php php-* /^php[1-9]+/
  mysql: mysql* libmysql*
  nginx: nginx*
  ruby: ruby*
  nodejs: nodejs*
  rabbitmq: rabbitmq*
  redis: redis*
  haproxy: haproxy*
  galera: galera*
  grafana: grafana*
  elasticsearch: elasticsearch*
  postgresql: postgresql*
  mongodb: mongodb*
  keepalived: keepalived*
  gitlab-ce: gitlab-ce*
  docker: docker*
  chrony: chrony*
  backup-manager: backup-manager*
  pam-ssh-agent-auth: libpam-ssh-agent-auth*
  cloud: cloud-init cloud-utils
  mariadb: mariadb* libmariadb*
  maxscale: maxscale*
  influxdb: influxdb*
  telegraf: telegraf*
  python-six: python-six*
  htop: htop*
  yarn: yarn*
  openssh: openssh*
  ansible: ansible*
  openjdk: openjdk-* ca-certificates-java
  linux: linux-base linux-image-* linux-headers-*
  certbot: >-
    certbot python-certbot python-acme python3-certbot python3-acme python-cryptography
    python-openssl python-setuptools python-pyasn1 python-pkg-resources
  thumbor: thumbor python-libthumbor
  mica: mica
  sensu-go: sensu-go-*
  ffmpeg: |-
    ffmpeg {{
      {
        'buster': 'libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libpostproc55 libswresample3 libswscale5',
        'bullseye': 'libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libpostproc55 libswresample3 libswscale5',
      }[ansible_distribution_release]
    }}
  glusterfs: glusterfs-*
  newrelic-infra: newrelic-infra
  filebeat: filebeat*
  kopia: kopia*
