---

- name: install > Packages
  apt:
    name: "{{ manala_composer_install_packages|default(manala_composer_install_packages_default, True) }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600

- name: install > Stat bin
  stat:
    path: "{{ manala_composer_bin }}"
  register: __manala_composer_bin_stat_result

- name: install > Download installer
  get_url:
    url:  https://getcomposer.org/installer
    dest: /tmp
  when: not __manala_composer_bin_stat_result.stat.exists

- name: install > Install
  command: "php /tmp/installer --install-dir=\"{{ manala_composer_bin|dirname }}\" --filename=\"{{ manala_composer_bin|basename }}\"{{ (manala_composer_version is none)|ternary('', ' --version=' + manala_composer_version|default('', true)) }}"
  when: not __manala_composer_bin_stat_result.stat.exists

- name: install > Remove installer
  file:
    path:  /tmp/installer
    state: absent
  when: not __manala_composer_bin_stat_result.stat.exists
