---

- name: keys > Keys
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url|default(omit) }}"
    keyserver: "{{ item.keyserver|default(omit) }}"
    validate_certs: "{{ item.validate_certs|default(omit) }}"
    state: "{{ item.state|default('present') }}"
  loop: "{{ query(
      'manala_apt_keys',
      manala_apt_keys,
      manala_apt_keys_patterns,
      query(
        'manala_apt_repositories',
        manala_apt_repositories,
        manala_apt_repositories_patterns,
        query(
            'manala_apt_preferences',
            manala_apt_preferences,
            manala_apt_preferences_patterns,
            manala_apt_repositories_patterns,
            [],
            manala_apt_preferences_dir,
            wantstate='present'
        ),
        [],
        wantstate='present'
      ),
    )
  }}"
