---

- name: repositories > Exclusive
  find:
    path: /etc/apt/sources.list.d
    patterns: "*.list"
  changed_when: false
  register: __manala_apt_repositories_exclusive_find
  when: manala_apt_repositories_exclusive

- name: repositories > Repositories presents
  apt_repository:
    repo: "{{ item.source }}"
    filename: "{{ (item.file|basename|splitext)[0] }}"
    update_cache: false
  loop: "{{ query(
      'manala_apt_repositories',
      manala_apt_repositories,
      manala_apt_repositories_patterns,
      query(
          'manala_apt_preferences',
          manala_apt_preferences,
          manala_apt_preferences_patterns,
          manala_apt_repositories_patterns,
          [],
          manala_apt_preferences_dir,
          wantstate='present'
      ),
      __manala_apt_repositories_exclusive_find.files|default([]),
      wantstate='present'
    )
  }}"
  register: __manala_apt_repositories_presents_results

- name: repositories > Repositories absents
  file:
    path: "{{ item.file }}"
    state: absent
  loop: "{{ query(
      'manala_apt_repositories',
      manala_apt_repositories,
      manala_apt_repositories_patterns,
      query(
          'manala_apt_preferences',
          manala_apt_preferences,
          manala_apt_preferences_patterns,
          manala_apt_repositories_patterns,
          [],
          manala_apt_preferences_dir,
          wantstate='present'
      ),
      __manala_apt_repositories_exclusive_find.files|default([]),
      wantstate='absent'
    )
  }}"
  register: __manala_apt_repositories_absents_results

- name: repositories > Update cache
  apt:
    update_cache: true
  when: __manala_apt_repositories_presents_results is changed or __manala_apt_repositories_absents_results is changed
