---

- name: configs > Templates
  template:
    src:  "{{ item.template|default(manala_phpmyadmin_configs_template) }}"
    dest: "{{ manala_phpmyadmin_configs_dir }}/{{ item.file }}"
  register: __manala_phpmyadmin_configs_templates_output
  with_items: "{{ manala_phpmyadmin_configs }}"

- name: configs > Exclusive - find files
  command: "find -type f -printf '%P\n'"
  args:
    chdir: "{{ manala_phpmyadmin_configs_dir }}"
  changed_when: false
  register: __manala_phpmyadmin_configs_find_output
  when: manala_phpmyadmin_configs_exclusive

- name: configs > Exclusive - remove files
  file:
    path:  "{{ manala_phpmyadmin_configs_dir }}/{{ item }}"
    state: absent
  when: manala_phpmyadmin_configs_exclusive and (item not in manala_phpmyadmin_configs|map(attribute='file'))
  with_items: "{{ __manala_phpmyadmin_configs_find_output.stdout_lines }}"
