---

- name: config > Template
  template:
    src:   "{{ manala_mongodb_config_template|ternary(manala_mongodb_config_template, 'config/base.conf.j2') }}"
    dest:  "{{ manala_mongodb_config_file }}"
  when: (manala_mongodb_config_template is not none) or (manala_mongodb_config|length)
  notify:
    - mongodb restart
