---

- name: config > Writing params file.
  copy:
    src:   "{{ item }}"
    dest:  /etc/shorewall/{{ item }}
    owner: root
    group: root
    mode:  0644
  with_items:
    - params

- name: config > Writing files.
  template:
    src:  "{{ item.src }}"
    dest: /etc/shorewall/{{ item.dest }}
  with_items:
    - { src: "{{ elao_shorewall_config_templates.policy }}",     dest: policy }
    - { src: "{{ elao_shorewall_config_templates.masq }}",       dest: masq }
    - { src: "{{ elao_shorewall_config_templates.interfaces }}", dest: interfaces }
    - { src: "{{ elao_shorewall_config_templates.zones }}",      dest: zones }
    - { src: "{{ elao_shorewall_config_templates.rules }}",      dest: rules }
  notify:
    - shorewall restart
