---

- name: configs > Templates
  template:
    src:  "{{ item.template|default('configs/empty.j2') }}"
    dest: "{{ manala_shorewall_configs_dir }}/{{ item.file }}"
  with_items: "{{ manala_shorewall_configs }}"
  notify:
    - shorewall restart
