---

- name: configs > Templates
  template:
    src:  "{{ item.template|default(manala_dnsmasq_configs_template) }}"
    dest: "{{ manala_dnsmasq_configs_dir }}/{{ item.file }}"
  with_items: "{{ manala_dnsmasq_configs }}"
  notify:
    - dnsmasq restart

- name: configs > Exclusive - find files
  command: "find -type f -printf '%P\n'"
  args:
    chdir: "{{ manala_dnsmasq_configs_dir }}"
  changed_when: false
  register: __manala_dnsmasq_configs_find_output
  when: manala_dnsmasq_configs_exclusive

- name: configs > Exclusive - remove files
  file:
    path:  "{{ manala_dnsmasq_configs_dir }}/{{ item }}"
    state: absent
  when: manala_dnsmasq_configs_exclusive and (item not in manala_dnsmasq_configs|map(attribute='file'))
  with_items: "{{ __manala_dnsmasq_configs_find_output.stdout_lines|default([]) }}"
  notify:
    - dnsmasq restart
