---

- name: errorfiles > Templates
  template:
    src:  "{{ item.template }}"
    dest: "{{ manala_haproxy_errorfiles_dir }}/{{ item.file }}"
  with_items: "{{ manala_haproxy_errorfiles }}"
  notify:
    - haproxy restart
