---

- name: hosts > File
  lineinfile:
    dest:   "{{ manala_network_hosts_file }}"
    regexp: "{{ item.keys()[0]|replace('.','\\.') }}"
    line:   "{{ item.keys()[0] }} {{ item.values()[0] }}"
  with_items: "{{ manala_network_hosts }}"
