---

- name: interfaces > Template
  template:
    src:  "{{ manala_network_interfaces_template|ternary(manala_network_interfaces_template, 'interfaces/empty.j2') }}"
    dest: "{{ manala_network_interfaces_file }}"
  when: (manala_network_interfaces_template is not none) or (manala_network_interfaces_config|length)
