---

- name: repositories > Key
  apt_key:
    id:             "{{ item.key }}"
    url:            "{{ item.value.url|default(omit) }}"
    keyserver:      "{{ item.value.keyserver|default(omit) }}"
    validate_certs: "{{ item.value.validate_certs|default(omit) }}"
    state:          "{{ item.value.state|default('present') }}"
  with_dict: "{{ __manala_apt_keys }}"
