---

- name: users > Accounts
  user:
    name:       "{{ item.name }}"
    password:   "{{ item.password|default(omit) }}"
    group:      "{{ item.group|default(omit) }}"
    groups:     "{{ item.groups|default([])|join(',') }}"
    shell:      "{{ item.shell|default(omit) }}"
    createhome: "{{ item.createhome|default(true)|bool }}"
    system:     "{{ item.system|default(false)|bool }}"
    uid:        "{{ item.uid|default(omit) }}"
    comment:    "{{ item.comment|default(omit) }}"
  with_items: "{{ elao_users }}"

- name: users > Authorized keys
  authorized_key:
    user:      "{{ item.0 }}"
    key:       "{{ item.1 }}"
    exclusive: true
  with_together:
    - "{{ elao_users|selectattr('authorized_keys', 'sequence')|map(attribute='name')|list }}"
    - "{{ elao_users|selectattr('authorized_keys', 'sequence')|map(attribute='authorized_keys')|map('join', '\n')|list }}"

# Find the primary group of users whose group has not been manually defined
- name: users > Find primary groups
  command: "id -g -n {{ item.name }}"
  with_items: "{{ elao_users }}"
  when: item.group is not defined
  register: __elao_users
  changed_when: false
  no_log: true

# Pair users with their found groups
- name: users > Pair primary groups
  set_fact:
    # Waiting for the ansible 2 "combine" filter...
    __item: "{% set __item = item.0.update(({}) if (item.1|skipped) else ({'group': item.1.stdout})) %}{{ item.0 }}"
  with_together:
    - "{{ elao_users }}"
    - "{{ __elao_users.results }}"
  register: __elao_users
  no_log: true

# Flatten results structure to the original variable
- name: users > Flatten primary groups
  set_fact:
    elao_users: "{{ __elao_users.results|map(attribute='ansible_facts.__item')|list }}"
  no_log: true

- name: users > Keys private
  copy:
    dest:    "~{{ item.0.name }}/.ssh/{{ item.1.name }}"
    content: "{{ item.1.private }}"
    owner:   "{{ item.0.name }}"
    group:   "{{ item.0.group|default(omit) }}"
    mode:    0600
  when: item.1.private is defined
  with_subelements:
    - "{{ elao_users|selectattr('keys', 'sequence')|list }}"
    - keys

- name: users > Keys public
  copy:
    dest:    "~{{ item.0.name }}/.ssh/{{ item.1.name }}.pub"
    content: "{{ item.1.public }}"
    owner:   "{{ item.0.name }}"
    group:   "{{ item.0.group|default(omit) }}"
    mode:    0644
  when: item.1.public is defined
  with_subelements:
    - "{{ elao_users|selectattr('keys', 'sequence')|list }}"
    - keys
