---

# Bin
manala_ansible_galaxy_bin: ~

# Roles
manala_ansible_galaxy_roles: []
manala_ansible_galaxy_roles_path: ~

# Force
manala_ansible_galaxy_force: "{{ __manala_ansible_galaxy['update'] }}"

# Flags
manala_ansible_galaxy: {}
