---

- name: configs > Templates
  template:
    src: "{{ item.template|default(manala_cloud_init_configs_template|ternary(manala_cloud_init_configs_template, 'configs/empty.j2')) }}"
    dest: "{{ manala_cloud_init_configs_dir }}/{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ manala_cloud_init_configs }}"

- name: configs > Exclusive - find files
  command: "find -type f -printf '%P\n'"
  args:
    chdir: "{{ manala_cloud_init_configs_dir }}"
  changed_when: false
  register: __manala_cloud_init_configs_find_output
  when: manala_cloud_init_configs_exclusive

- name: configs > Exclusive - remove files
  file:
    path: "{{ manala_cloud_init_configs_dir }}/{{ item }}"
    state: absent
  when: manala_cloud_init_configs_exclusive and (item not in manala_cloud_init_configs|map(attribute='file'))
  with_items: "{{ __manala_cloud_init_configs_find_output.stdout_lines|default([]) }}"
