---

# Setup For Debian
- include_tasks: setup-debian.yaml
  when: ansible_distribution == 'Debian'

# Install
- import_tasks: install.yml
  tags:
    - manala_mongodb

# Config
- import_tasks: config.yml
  tags:
    - manala_mongodb

# Services
- import_tasks: services.yml
  tags:
    - manala_mongodb
    - manala_mongodb.services
    - manala.services
