---

- name: instances > Manage proxmox VE instances
  proxmox:
    api_host: "{{ item.api_host|default(manala_proxmox_instances_defaults.api_host) }}"
    api_password: "{{ item.api_password|default(manala_proxmox_instances_defaults.api_password|default(omit)) }}"
    api_user: "{{ item.api_user|default(manala_proxmox_instances_defaults.api_user) }}"
    cores: "{{ item.cores|default(manala_proxmox_instances_defaults.cores|default(omit)) }}"
    cpus: "{{ item.cpus|default(manala_proxmox_instances_defaults.cpus|default(omit)) }}"
    cpuunits: "{{ item.cpuunits|default(manala_proxmox_instances_defaults.cpuunits|default(omit)) }}"
    disk: "{{ item.disk|default(manala_proxmox_instances_defaults.disk|default(omit)) }}"
    force: "{{ item.force|default(manala_proxmox_instances_defaults.force|default(omit)) }}"
    hostname: "{{ item.hostname|default(omit) }}"
    ip_address: "{{ item.ip_address|default(omit) }}"
    memory: "{{ item.memory|default(manala_proxmox_instances_defaults.memory|default(omit)) }}"
    mounts: "{{ item.mounts|default(manala_proxmox_instances_defaults.mounts|default(omit)) }}"
    nameserver: "{{ item.nameserver|default(manala_proxmox_instances_defaults.nameserver|default(omit)) }}"
    netif: "{{ item.netif|default(manala_proxmox_instances_defaults.netif|default(omit)) }}"
    node: "{{ item.node|default(manala_proxmox_instances_defaults.node|default(omit)) }}"
    onboot: "{{ item.onboot|default(manala_proxmox_instances_defaults.onboot|default(omit)) }}"
    ostemplate: "{{ item.ostemplate|default(manala_proxmox_instances_defaults.ostemplate|default(omit)) }}"
    password: "{{ item.password|default(manala_proxmox_instances_defaults.password|default(omit)) }}"
    pool: "{{ item.pool|default(manala_proxmox_instances_defaults.pool|default(omit)) }}"
    pubkey: "{{ item.pubkey|default(manala_proxmox_instances_defaults.pubkey|default(omit)) }}"
    searchdomain: "{{ item.searchdomain|default(manala_proxmox_instances_defaults.searchdomain|default(omit)) }}"
    state: "{{ item.state|default(manala_proxmox_instances_defaults.state|default(omit)) }}"
    storage: "{{ item.storage|default(manala_proxmox_instances_defaults.storage|default(omit)) }}"
    swap: "{{ item.swap|default(manala_proxmox_instances_defaults.swap|default(omit)) }}"
    timeout: "{{ item.timeout|default(manala_proxmox_instances_defaults.timeout|default(omit)) }}"
    unprivileged: "{{ item.unprivileged|default(manala_proxmox_instances_defaults.unprivileged|default(omit)) }}"
    validate_certs: "{{ item.validate_certs|default(manala_proxmox_instances_defaults.validate_certs|default(omit)) }}"
    vmid: "{{ item.vmid|default(omit) }}"
  with_items: "{{ manala_proxmox_instances }}"
  register: __manala_proxmox_instances_result
  until: __manala_proxmox_instances_result.msg.find('Vmid could not be fetched') == -1
  retries: 12
  delay: 1
