---

# Install
manala_beanstalkd_install_packages: ~
manala_beanstalkd_install_packages_default:
  - beanstalkd

# Config
manala_beanstalkd_config_file: /etc/default/beanstalkd
manala_beanstalkd_config_template: ~
manala_beanstalkd_config: []
