---

dependencies: []

galaxy_info:

  role_name: composer
  author: Manala
  company: Manala
  description: Handle composer
  license: MIT
  min_ansible_version: 2.4.0
  issue_tracker_url: https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - development
    - composer
    - php
