---

- name: config > Template
  template:
    src:  "{{ manala_haproxy_config_template }}"
    dest: "{{ manala_haproxy_config_file }}"
  notify:
    - haproxy restart
  when: manala_haproxy_config_template is not none
