---

# Install
manala_bind_install_packages: ~
manala_bind_install_packages_default:
  - bind9

# User / Group
manala_bind_user: bind
manala_bind_group: bind

# Options
manala_bind_options_file: /etc/default/{{ (ansible_distribution_release in ['buster']) | ternary('bind9', 'named') }}
manala_bind_options:
  - -u {{ manala_bind_user }}

# Logs
manala_bind_log_dir: /var/log/bind

# Configs
manala_bind_configs_dir: /etc/bind
manala_bind_configs: []

# Zones
manala_bind_zones_dir: /var/cache/bind
manala_bind_zones: []
