---

# Install
- import_tasks: install.yml
  tags:
    - manala_influxdb

# Config
- import_tasks: config.yml
  tags:
    - manala_influxdb

# Services
- import_tasks: services.yml
  tags:
    - manala_influxdb
    - manala_influxdb.services
    - manala.services

# Databases
- import_tasks: databases.yml
  tags:
    - manala_influxdb

# Users
- import_tasks: users.yml
  tags:
    - manala_influxdb

# Privileges
- import_tasks: privileges.yml
  tags:
    - manala_influxdb
