---

# Install
manala_shorewall_install_packages: ~
manala_shorewall_install_packages_default:
  - shorewall

# Configs
manala_shorewall_configs_exclusive: false
manala_shorewall_configs_dir: /etc/shorewall
manala_shorewall_configs_defaults: {}
manala_shorewall_configs: []

# Config
manala_shorewall_config_file: /etc/shorewall/shorewall.conf
manala_shorewall_config: {}
