---

dependencies: []

galaxy_info:

  role_name: sensu_go
  author: Manala
  company: Manala
  description: Install and configure sensu
  license: MIT
  min_ansible_version: 2.18.0
  issue_tracker_url: https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - alerting
    - monitoring
    - system
    - sensugo
    - sensu
