---

- name: RedHat > codes > Currents
  command: "locale --all-locales"
  changed_when: false
  check_mode: false
  register: __manala_locales_codes_locale_output

- name: RedHat > codes > Handle
  command: "{{
    (
      'localedef --force --inputfile ' ~ item.code.split('.')[0] ~ (' --charmap ' ~ item.code.split('.')[1] ~ ' ' if (item.code.split('.')|length > 1) else ' ') ~ item.code
        if (item.state == 'present') else
      'localedef --delete-from-archive ' ~ item.code_denormalized|default(item.code)
    ) if (item.state != item.state_current and not ansible_check_mode) else 'true'
    }}"
  register: __manala_locales_codes_localedef_output
  failed_when: __manala_locales_codes_localedef_output.rc > 1
  changed_when: item.state != item.state_current
  check_mode: false
  with_items: "{{ lookup(
      'manala_locales_codes',
      manala_locales_codes,
      __manala_locales_codes_locale_output.stdout_lines|default([]),
      wantcodedenormalized=True,
      wantstatecurrent=True,
      wantlist=True
    )
  }}"
