---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - manala_ngrok
    - manala_ngrok.install

- name: Configs
  ansible.builtin.import_tasks: configs.yml
  tags:
    - manala_ngrok
    - manala_ngrok.configs
