---

# Configs
manala_apt_configs_exclusive: false
manala_apt_configs_dir: /etc/apt/apt.conf.d
manala_apt_configs_defaults: {}
manala_apt_configs: []

# Install
manala_apt_install_packages: ~
manala_apt_install_packages_default:
  - apt-transport-https
  - openssl
  - ca-certificates
  - gnupg

# Components
manala_apt_components: ['main']

# Sources list
manala_apt_sources_list_file: /etc/apt/sources.list
manala_apt_sources_list_template: ~
manala_apt_sources_list: ~

# Repositories
manala_apt_repositories_exclusive: false
manala_apt_repositories: []

# Preferences
manala_apt_preferences_exclusive: false
manala_apt_preferences_dir: /etc/apt/preferences.d
manala_apt_preferences_defaults: {}
manala_apt_preferences: []

# Keys
manala_apt_keys: []

# Holds
manala_apt_holds_exclusive: false
manala_apt_holds: []

# Update
manala_apt_update_holds: []

# Packages
manala_apt_packages: []

# Cache
manala_apt_cache_valid_time: 3600

# Flags
manala_apt: {}
