services:

    ##########
    # System #
    ##########

    system:
        build:
            args:
                MANALA_USER_ID: ${MANALA_USER_ID:-1000}
                MANALA_GROUP_ID: ${MANALA_GROUP_ID:-1000}
