---

dependencies: []

galaxy_info:

  role_name: ntp
  author: Manala
  company: Manala
  description: Handle ntp
  license: MIT
  min_ansible_version: 2.18.0
  issue_tracker_url: https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - system
    - ntp
