---

# Install
manala_sensu_go_install_packages: ~
manala_sensu_go_install_packages_default: "{{
  ['sensu-go-agent']
  + (manala_sensu_go_backend)|ternary(
    ['sensu-go-backend', 'sensu-go-cli'],
    []
  )
}}"

# Backend Config
manala_sensu_go_backend:                 false
manala_sensu_go_backend_config_template: ~
manala_sensu_go_backend_config_file:     /etc/sensu/backend.yml
manala_sensu_go_backend_config:          {}

# Agent Config
manala_sensu_go_agent_config_template:   ~
manala_sensu_go_agent_config_file:       /etc/sensu/agent.yml
manala_sensu_go_agent_config:            {}

# Services
manala_sensu_go_services:          []
