---

- name: configs > Directory
  file:
    path: "{{ manala_mysql_configs_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: manala_mysql_configs|length

- name: configs > Exclusive
  find:
    path: "{{ manala_mysql_configs_dir }}"
    file_type: file
    patterns: "*"
  changed_when: false
  register: __manala_mysql_configs_exclusive_find
  when: manala_mysql_configs_exclusive

- name: configs > Templates present
  template:
    src: "{{ item.template }}"
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ query(
    'manala.roles.templates_exclusive',
    manala_mysql_configs,
    __manala_mysql_configs_exclusive_find.files|default([]),
    manala_mysql_configs_dir,
    manala_mysql_configs_defaults.template|default('configs/_default.j2', true),
    wantstate='present'
  ) }}"
  register: __manala_mysql_configs_templates_present_result

- name: configs > Files absent
  file:
    path: "{{ item.file }}"
    state: absent
  loop: "{{ query(
    'manala.roles.templates_exclusive',
    manala_mysql_configs,
    __manala_mysql_configs_exclusive_find.files|default([]),
    manala_mysql_configs_dir,
    manala_mysql_configs_defaults.template|default('configs/_default.j2', true),
    wantstate='absent'
  ) }}"
  register: __manala_mysql_configs_files_absent_result
