---

- name: configs > Directory
  file:
    path: "{{ manala_mysql_configs_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: manala_mysql_configs|length

- name: configs > Exclusive
  find:
    path: "{{ manala_mysql_configs_dir }}"
    patterns: "*"
  changed_when: false
  register: __manala_mysql_configs_exclusive_find
  when: manala_mysql_configs_exclusive

- name: configs > Templates present
  template:
    src: "{{ item.template|default(manala_mysql_configs_template|ternary(manala_mysql_configs_template, 'configs/empty.j2')) }}"
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ query(
      'manala_mysql_configs',
      manala_mysql_configs,
      __manala_mysql_configs_exclusive_find.files|default([]),
      manala_mysql_configs_dir,
      wantstate='present'
    )
  }}"
  when: item.content is not defined
  notify:
    - mysql restart

- name: configs > Contents present
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ query(
      'manala_mysql_configs',
      manala_mysql_configs,
      __manala_mysql_configs_exclusive_find.files|default([]),
      manala_mysql_configs_dir,
      wantstate='present'
    )
  }}"
  when: item.content is defined
  notify:
    - mysql restart

- name: configs > Files absent
  file:
    path: "{{ item.file }}"
    state: absent
  loop: "{{ query(
      'manala_mysql_configs',
      manala_mysql_configs,
      __manala_mysql_configs_exclusive_find.files|default([]),
      manala_mysql_configs_dir,
      wantstate='absent'
    )
  }}"
  notify:
    - mysql restart
