---

- name: databases > Create mysql databases
  mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding|default('utf8') }}"
    collation: "{{ item.collation|default('utf8_general_ci') }}"
    state: "{{ item.state|default(omit) }}"
  loop: "{{
    manala_mysql_databases | flatten | selectattr('state', 'undefined') | list
    +
    manala_mysql_databases | flatten | selectattr('state', 'defined') | rejectattr('state', 'eq', 'ignore') | list
  }}"

