---

- name: Databases > Create mysql databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    sql_log_bin: "{{ item.sql_log_bin | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    # Login
    login_host: "{{ item.login_host | default(manala_mysql_login_host | default(omit, True), True) }}"
    login_port: "{{ item.login_port | default(manala_mysql_login_port | default(omit, True), True) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(manala_mysql_login_unix_socket | default(omit, True), True) }}"
    login_user: "{{ item.login_user | default(manala_mysql_login_user | default(omit, True), True) }}"
    login_password: "{{ item.login_password | default(manala_mysql_login_password | default(omit, True), True) }}"
  loop: "{{
    manala_mysql_databases
      | flatten
      | manala.roles.staten
  }}"
  when: manala_mysql_server
