---

- name: install > Packages
  apt:
    name: "{{ item }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
  loop:
    - "{{
      manala_mysql_install_packages|default(manala_mysql_install_packages_default, True)
      + (
        (manala_mysql_users|length > 0)
        or (manala_mysql_databases|length > 0)
        or (manala_mysql_replications|length > 0)
      )|ternary(
        (ansible_python.version.major == 2)|ternary(
          ['python-pymysql'],
          ['python3-pymysql']
        ),
        []
      )
    }}"
