---

# Install
- import_tasks: install.yml
  tags:
    - manala_glusterfs
    - manala_glusterfs.install

# Services
- import_tasks: services.yml
  tags:
    - manala_glusterfs
    - manala_glusterfs.services

# Volumes
- import_tasks: volumes.yml
  tags:
    - manala_glusterfs
    - manala_glusterfs.volumes
