---

- name: files > Jobs
  cron:
    cron_file:  "{{ item.0.file }}"
    name:       "{{ item.1.name }}"
    job:        "{{ item.1.job }}"
    minute:     "{{ item.1.minute|default(omit) }}"
    hour:       "{{ item.1.hour|default(omit) }}"
    day:        "{{ item.1.day|default(omit) }}"
    month:      "{{ item.1.month|default(omit) }}"
    weekday:    "{{ item.1.weekday|default(omit) }}"
    user:       "{{ item.0.user|default('root') }}"
    state:      "{{ item.1.state|default('present') }}"
  with_subelements:
    - "{{ manala_cron_files }}"
    - jobs
  notify:
    - cron restart

- name: files > Env variables
  cronvar:
    cron_file: "{{ item.file }}"
    name:      "{{ item.name }}"
    value:     "{{ item.value }}"
    user:      "{{ item.user|default(omit) }}"
    state:     present
  with_manala_cron_files_env:
    - "{{ manala_cron_files }}"
  notify:
    - cron restart

# Deprecated
- name: files > Environment variables (deprecated)
  cronvar:
    cron_file: "{{ item.0.file }}"
    name:      "{{ item.1.keys()[0] }}"
    value:     "{{ item.1.values()[0] }}"
    user:      "{{ item.0.user|default(omit) }}"
    state:     present
  with_subelements:
    - "{{ manala_cron_files }}"
    - environment
    - skip_missing: true
  notify:
    - cron restart
