---

# Install
manala_mongodb_install_packages: ~
manala_mongodb_install_packages_default:
  - mongodb-org
  - mongodb-org-server
  - mongodb-org-shell
  - mongodb-org-tools

# Config
manala_mongodb_config_file: /etc/mongod.conf
manala_mongodb_config_template: ~
manala_mongodb_config: ~

# Users
manala_mongodb_users: []
