---

dependencies: []

galaxy_info:

  role_name: ansible
  author: Manala
  company: Manala
  description: Handle ansible
  license: MIT
  min_ansible_version: 2.10.0
  issue_tracker_url: https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
  galaxy_tags:
    - system
    - ansible
