---

- name: install > Packages
  apt:
    name: "{{ manala_elasticsearch_install_packages|default(manala_elasticsearch_install_packages_default, True) }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600

- block:
    - name: install > Version
      shell: "dpkg -s elasticsearch | grep \"Version: \" | sed -e 's/Version: //g'"
      register: __manala_elasticsearch_version
      changed_when: false
    - name: install > Version
      set_fact:
        manala_elasticsearch_version: "{{
          __manala_elasticsearch_version.stdout.split('.')[0] ~ '.' ~ __manala_elasticsearch_version.stdout.split('.')[1]
            if (__manala_elasticsearch_version.stdout is version('2.0.0', '<')) else
          __manala_elasticsearch_version.stdout.split('.')[0]
        }}"
      changed_when: false
  when: manala_elasticsearch_version is none
  check_mode: false
