---

# Requirements
- import_tasks: requirements.yml
  tags:
    - manala_elasticsearch

# Install
- import_tasks: install.yml
  tags:
    - manala_elasticsearch

# Config
- import_tasks: config.yml
  tags:
    - manala_elasticsearch

# Services
- import_tasks: services.yml
  tags:
    - manala_elasticsearch
    - manala_elasticsearch.services
    - manala.services

# Plugins
- import_tasks: plugins.yml
  tags:
    - manala_elasticsearch
