---

# Alternatives
- import_tasks: alternatives.yml
  tags:
    - manala_ansible_galaxy
    # Ensure alternatives in update mode
    - manala_ansible_galaxy.update
    - manala.update

# Roles
- import_tasks: roles.yml
  tags:
    - manala_ansible_galaxy
    - manala_ansible_galaxy.update
    - manala.update
