---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600
  with_items: "{{ manala_rsyslog_install_packages|default(manala_rsyslog_install_packages_default, True) }}"
