---

- name: config > Template
  ansible.builtin.template:
    src: "{{ manala_elasticsearch_config_template | default('config/_default.j2', true) }}"
    dest: "{{ manala_elasticsearch_config_file }}"
    owner: root
    group: elasticsearch
    mode: "{{
      '0750' if (manala_elasticsearch_version is version('2', '=')) else
      '0660'
    }}"
  when: manala_elasticsearch_config_template
    or manala_elasticsearch_config
  notify:
    - elasticsearch restart
