---

- name: plugins > Install
  elasticsearch_plugin:
    name: "{{ (item) if (item is string) else (item.name) }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ manala_elasticsearch_plugins }}"
  notify:
    - elasticsearch restart
