---

- name: config > PostgreSQL configuration
  template:
    src: "{{ manala_postgresql_config_template }}"
    dest: /etc/postgresql/{{ manala_postgresql_version }}/main/postgresql.conf
  when: manala_postgresql_config_template is not none
  register: __manala_postgresql_config_result

- name: config > PostgreSQL host-based authentication (hba) configuration
  template:
    src: "{{ manala_postgresql_config_hba_template }}"
    dest: /etc/postgresql/{{ manala_postgresql_version }}/main/pg_hba.conf
  when: manala_postgresql_config_hba_template is not none
  register: __manala_postgresql_config_hba_result

- name: config > Restart service
  service:
    name:  postgresql
    state: restarted
  when: __manala_postgresql_config_result.changed or __manala_postgresql_config_hba_result.changed
