---

- name: install > Packages
  apt:
    name: "{{ manala_redis_install_packages|default(manala_redis_install_packages_default, True) }}"
    install_recommends: false
    update_cache:       true
    cache_valid_time:   3600

- block:
    - name: install > Version
      shell: redis-server -v | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
      register: __manala_redis_version
      changed_when: false
    - name: install > Version
      set_fact:
        manala_redis_version: "{{ (__manala_redis_version.stdout == '')|ternary('3.0', __manala_redis_version.stdout) }}"
      changed_when: false
  when: manala_redis_version is none
  check_mode: false
