---

# Version
manala_postgresql_version: ~

# Install
manala_postgresql_install_packages: ~
manala_postgresql_install_packages_default:
  - postgresql-{{ manala_postgresql_version }}
  - postgresql-contrib-{{ manala_postgresql_version }}

# Config
manala_postgresql_config_file: /etc/postgresql/{{ manala_postgresql_version }}/main/postgresql.conf
manala_postgresql_config_template: ~
manala_postgresql_config: ~
manala_postgresql_config_hba_file: /etc/postgresql/{{ manala_postgresql_version }}/main/pg_hba.conf
manala_postgresql_config_hba_template: ~
manala_postgresql_config_hba: ~

# Login
manala_postgresql_login_host: localhost

# Roles
manala_postgresql_roles: []

# Databases
manala_postgresql_databases: []

# Privileges
manala_postgresql_privileges: []
