---

- name: install > Packages presents
  apt:
    name: "{{
      query(
        'manala_php_packages',
        (
          query(
            'manala_php_sapis',
            manala_php_sapis|default(manala_php_sapis_default, True),
            manala_php_sapis_available,
            wantstate='present',
            wantmap=true
          )
          + query(
            'manala_php_extensions',
            manala_php_extensions,
            manala_php_extensions_available,
            manala_php_sapis_available,
            wantstate='present',
            wantmap=true
          )
        ),
        manala_php_version|string,
        manala_php_extensions_pecl_available,
        manala_php_extensions_pecl_versioned
      )
    }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600

- name: install > Packages absents
  apt:
    name: "{{
      query(
        'manala_php_packages',
        (
          query(
            'manala_php_sapis',
            manala_php_sapis|default(manala_php_sapis_default, True),
            manala_php_sapis_available,
            wantstate='absent',
            wantmap=true
          )
          + query(
            'manala_php_extensions',
            manala_php_extensions,
            manala_php_extensions_available,
            manala_php_sapis_available,
            wantstate='absent',
            wantmap=true
          )
        ),
        manala_php_version|string,
        manala_php_extensions_pecl_available,
        manala_php_extensions_pecl_versioned
      )
    }}"
    state: absent
    purge: true
    autoremove: true

# Use dpkg-query to find out installed packages
- name: install > Exclusive - Packages presents
  command: dpkg-query --showformat "${Status}    ${binary:Package}\n" --show "php*"
  register: __manala_php_install_packages_presents_result
  check_mode: false
  changed_when: false
  when: manala_php_sapis_exclusive or manala_php_extensions_exclusive

# Ensure debfoster is presents if exclusive mode is set
- name: install > Exclusive - Packages requirements
  apt:
    name:
      - debfoster
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
  when: manala_php_sapis_exclusive or manala_php_extensions_exclusive

# Use debfoster to find out each package dependencies
- name: install > Exclusive - Packages dependencies
  shell: |
    for package in {{
      query(
        'manala_php_packages',
        (
          query(
            'manala_php_sapis',
            manala_php_sapis|default(manala_php_sapis_default, True),
            manala_php_sapis_available,
            wantstate='present',
            wantmap=true
          )
          + query(
            'manala_php_extensions',
            manala_php_extensions,
            manala_php_extensions_available,
            manala_php_sapis_available,
            wantstate='present',
            wantmap=true
          )
        ),
        manala_php_version|string,
        manala_php_extensions_pecl_available,
        manala_php_extensions_pecl_versioned
      )|join(' ')
    }}
    do
       debfoster --quiet --option UseRecommends=no --show-depends $package
    done
  register: __manala_php_install_packages_dependencies_result
  check_mode: false
  changed_when: false
  when: manala_php_sapis_exclusive or manala_php_extensions_exclusive

- name: install > Exclusive - Packages absents
  apt:
    name: "{{
      query(
        'manala_php_packages_exclusive',
        query(
          'manala_php_packages',
          (
            query(
              'manala_php_sapis',
              manala_php_sapis|default(manala_php_sapis_default, True),
              manala_php_sapis_available,
              wantstate='present',
              wantmap=true
            )
            + query(
              'manala_php_extensions',
              manala_php_extensions,
              manala_php_extensions_available,
              manala_php_sapis_available,
              wantstate='present',
              wantmap=true
            )
          ),
          manala_php_version|string,
          manala_php_extensions_pecl_available,
          manala_php_extensions_pecl_versioned
        ),
        query(
          'manala_php_packages',
          manala_php_sapis_available,
          manala_php_version|string,
          manala_php_extensions_pecl_available,
          manala_php_extensions_pecl_versioned
        ),
        __manala_php_install_packages_presents_result.stdout_lines|default([]),
        __manala_php_install_packages_dependencies_result.stdout_lines|default([]),
        manala_php_sapis_exclusive,
        manala_php_extensions_exclusive
      )
    }}"
    state: absent
    purge: true
    autoremove: true
  when: manala_php_sapis_exclusive or manala_php_extensions_exclusive
