---

- name: strategy/git > Cached repository
  git:
    repo:           "{{ manala_deploy_strategy_git_repo }}"
    dest:           "{{ deploy_helper.shared_path ~ '/cached-copy' }}"
    version:        "{{ manala_deploy_strategy_git_version }}"
    accept_hostkey: true
    update:         true

- name: strategy/git > Export repository
  command: git checkout-index -f -a --prefix="{{ deploy_helper.new_release_path }}/"
  args:
    chdir: "{{ deploy_helper.shared_path ~ '/cached-copy' }}"
