---

- name: Install > Stat bin
  ansible.builtin.stat:
    path: "{{ manala_vault_cli_bin }}"
  register: __manala_vault_cli_bin_stat_result

- name: Install > Get latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/hashicorp/vault/releases/latest
  check_mode: false
  register: __manala_vault_cli_version_latest
  when:
    - not __manala_vault_cli_bin_stat_result.stat.exists
    - manala_vault_cli_version is none

- name: Install > Install
  when: not __manala_vault_cli_bin_stat_result.stat.exists
  vars:
    __manala_vault_cli_version: |-
      {{
        manala_vault_cli_version
          if (manala_vault_cli_version) else
        __manala_vault_cli_version_latest.json.tag_name | regex_replace('v(.+)$', '\1')
      }}
    __manala_vault_cli_archive: |-
      {{
        'vault_%(version)s_linux_%(architecture)s' | format(
          version=__manala_vault_cli_version,
          architecture=ansible_architecture | manala.roles.vault_cli_architecture,
        )
      }}
    __manala_vault_cli_archive_url: |-
      {{
        'https://releases.hashicorp.com/vault/%(version)s/%(archive)s.zip' | format(
          version=__manala_vault_cli_version,
          archive=__manala_vault_cli_archive,
        )
      }}
    __manala_vault_cli_archive_bin: vault
  block:

    - name: Install > Create temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: __manala_vault_cli_temporary_directory

    - name: Install > Download to temporary directory
      ansible.builtin.unarchive:
        src: "{{ __manala_vault_cli_archive_url }}"
        remote_src: true
        dest: "{{ __manala_vault_cli_temporary_directory.path }}"

    - name: Install > Copy binary
      ansible.builtin.copy:
        src: "{{ __manala_vault_cli_temporary_directory.path }}/{{ __manala_vault_cli_archive_bin }}"
        remote_src: true
        dest: "{{ manala_vault_cli_bin }}"
        owner: root
        group: root
        mode: "0755"

    - name: Install > Delete temporary directory
      ansible.builtin.file:
        path: "{{ __manala_vault_cli_temporary_directory.path }}"
        state: absent
