---

# Version
manala_php_version: ~

# Sapis
manala_php_sapis_exclusive: false
manala_php_sapis: ~
manala_php_sapis_default:
  - cli
  - fpm

# Extensions
manala_php_extensions_exclusive: false
manala_php_extensions: []

# Configs
manala_php_configs_exclusive: false
manala_php_configs_dir: /etc/php/{{ manala_php_version | string }}
manala_php_configs_defaults: {}
manala_php_configs: []
manala_php_cli_configs: []
manala_php_fpm_configs: []

# Fpm pools
manala_php_fpm_pools_exclusive: false
manala_php_fpm_pools_dir: /etc/php/{{ manala_php_version | string }}/fpm/pool.d
manala_php_fpm_pools_defaults: {}
manala_php_fpm_pools: []

# Blackfire
manala_php_blackfire: false

manala_php_blackfire_agent_config_file: /etc/blackfire/agent
manala_php_blackfire_agent_config_template: ~
manala_php_blackfire_agent_config: ~

manala_php_blackfire_client_config_file: ~/.blackfire.ini
manala_php_blackfire_client_config_template: ~
manala_php_blackfire_client_config: ~

# Applications
manala_php_applications_dir: /usr/local/bin
manala_php_applications: []
