---

dependencies: []

galaxy_info:

  role_name:           rtail
  author:              Manala
  company:             Manala
  description:         Handle rtail
  license:             MIT
  min_ansible_version: 2.4.0
  issue_tracker_url:   https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - development
    - web
    - rtail
