---

- name: configs > Directory
  file:
    path: "{{ manala_telegraf_configs_dir }}"
    state: directory
  when: manala_telegraf_configs|length

- name: configs > Exclusive
  find:
    path: "{{ manala_telegraf_configs_dir }}"
    patterns: "*.conf"
  changed_when: false
  register: __manala_telegraf_configs_exclusive_find
  when: manala_telegraf_configs_exclusive

- name: configs > Templates present
  template:
    src:  "{{ item.template|default(manala_telegraf_configs_template|ternary(manala_telegraf_configs_template, 'configs/empty.j2')) }}"
    dest: "{{ item.file }}"
  loop: "{{ query(
      'manala_telegraf_configs',
      manala_telegraf_configs,
      __manala_telegraf_configs_exclusive_find.files|default([]),
      manala_telegraf_configs_dir,
      wantstate='present'
    )
  }}"
  # notify:
  #   - telegraf restart

# Ansible template module does not support "state" parameter (see: https://github.com/ansible/ansible/issues/29781)
- name: configs > Files absent
  file:
    path:  "{{ item.file }}"
    state: absent
  loop: "{{ query(
      'manala_telegraf_configs',
      manala_telegraf_configs,
      __manala_telegraf_configs_exclusive_find.files|default([]),
      manala_telegraf_configs_dir,
      wantstate='absent'
    )
  }}"
  # notify:
  #   - telegraf restart
