---

dependencies: []

galaxy_info:

  role_name:           varnish
  author:              Manala
  company:             Manala
  description:         Setup and config for Varnish
  license:             MIT
  min_ansible_version: 2.5.0
  issue_tracker_url:   https://github.com/manala/ansible-roles/issues
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
  galaxy_tags:
    - development
    - web
    - webperf
